'@stijnvanhulle/components':
  - any: ['packages/components/**', '!packages/components/package.json']

'@stijnvanhulle/platform':
  - any: ['apps/platform/**', '!apps/platform/package.json']

'@internals/utils':
  - any: ['internals/utils/**']

docs:
  - any: ['README.md', '*.md', 'docs/**']

ci:
  - any: ['.github/**']

feature:
  - head-branch: ['^feat', 'feat']

bug:
  - head-branch: ['^bug', 'bug', '^fix', 'fix']

chore:
  - head-branch: ['^chore', 'chore']
